Repository msupply-foundation/mobile, pull requests merged in 2019-04, with the labels that each got.

#846 #840 - VVN Component
  src/widgets/MiniToggleBar.js
Labels: Feature

#847 #838 introduce db schema changes for vaccine module
  src/database/DataTypes/Item.js
  src/database/DataTypes/ItemBatch.js
  src/database/DataTypes/Location.js
  src/database/DataTypes/LocationType.js
  src/database/DataTypes/Sensor.js
  src/database/DataTypes/SensorLog.js
  src/database/DataTypes/TransactionBatch.js
  src/database/DataTypes/index.js
  src/database/schema.js
  src/pages/RealmExplorer.js
  src/sync/SyncQueue.js
  src/sync/incomingSyncUtils.js
  src/sync/outgoingSyncUtils.js
  src/sync/syncTranslators.js
Labels: Vaccine Module

#853 #852 - fix dodgy if statement
  src/sync/outgoingSyncUtils.js
Labels: Vaccine Module

#866 #865 class helper methods
  src/database/DataTypes/Item.js
  src/database/DataTypes/ItemBatch.js
  src/database/DataTypes/Transaction.js
Labels: Vaccine Module

#864 #863 fix description field on Location and LocationType
  src/sync/incomingSyncUtils.js
Labels: Vaccine Module

#854 #848 vaccine module generic chart
  .eslintrc
  android/app/build.gradle
  android/app/src/main/java/com/msupplymobile/MainApplication.java
  android/settings.gradle
  ios/mSupplyMobile.xcodeproj/project.pbxproj
  package.json
  src/pages/MenuPage.js
  src/pages/index.js
  src/widgets/HazardPoint.js
  src/widgets/VaccineChart.js
  yarn.lock
Labels: Vaccine Module

#868 #867 add customisations to menu page
  src/images/menu_modules.png
  src/localization/navStrings.js
  src/pages/MenuPage.js
  src/settings/index.js
  src/sync/incomingSyncUtils.js
  src/sync/syncTranslators.js
Labels: Vaccine Module

#869 #858 Manage vaccine stock page
  src/database/DataTypes/Item.js
  src/pages/ManageStockPage.js
  src/utilities/formatStatus.js
  src/utilities/formatters.js
  src/utilities/index.js
  src/widgets/GenericChoiceList.js
  src/widgets/index.js
Labels: Vaccine Module

#881 #843 helper methods
  src/utilities/modules/vaccines.js
Labels: Vaccine Module

#899 #894 SupplierInvoicePage: GenericChoiceList over AutoCompleteSelector
  src/pages/SupplierInvoicePage.js
Labels: Ivory Coast (phase 1)

#901 #896 refactor vaccine chart
  src/globalStyles/colors.js
  src/globalStyles/index.js
  src/widgets/HazardPoint.js
  src/widgets/VaccineChart.js
Labels: Vaccine Module

#884 #878 aggregate sensor data
  src/utilities/aggregateLogs.js
Labels: Vaccine Module

#913 #911 - Breach modal integration
  src/pages/ManageVaccineItemPage.js
  src/pages/ManageVaccineStockPage.js
Labels: Vaccine Module

#931 Ic cmm calculation
  src/database/DataTypes/Item.js
  src/settings/MobileAppSettings.js
  src/sync/incomingSyncUtils.js
Labels: Docs: needed

#821 #820 Item DefaultPrice is synced incorrectly
  src/database/DataTypes/Item.js
  src/sync/incomingSyncUtils.js
  src/widgets/AutocompleteSelector.js
  src/widgets/OnePressButton.js
Labels: Bug
