Repository msupply-foundation/mobile, pull requests merged in 2019-10, with the labels that each got.

#1438 #1398 rename unsafe lifecycle methods
  src/pages/MenuPage.js
  src/widgets/Spinner.js
  src/widgets/modals/BottomModal.js
  src/widgets/modals/DemoUserModal.js
  src/widgets/modals/LoginModal.js
Labels: Docs: needed, Effort: small, Priority: Normal

#1453 #1449 hotfix remove hardware id settings
  src/authentication/SyncAuthenticator.js
  src/authentication/UserAuthenticator.js
  src/settings/MobileAppSettings.js
  src/settings/index.js
  src/sync/Synchroniser.js
Labels: Bug: production, Docs: not needed, Effort: small

#1452 #1449 remove DeviceInfo from settings
  src/authentication/SyncAuthenticator.js
  src/authentication/UserAuthenticator.js
  src/sync/Synchroniser.js
Labels: Bug: production, Docs: not needed, Effort: small

#1470 #1467 Footer to DataTable
  src/widgets/DataTable/DataTable.js
Labels: Priority: Immediate

#1469 #1464 Add update to stocktake manager navigation to replace
  src/navigation/actions.js
Labels: Priority: Immediate

#1468 #1463 Editable when finalised
  src/widgets/modals/StocktakeBatchModal.js
Labels: Priority: Immediate
