Repository msupply-foundation/mobile, pull requests merged in 2019-09, with the labels that each got.

#1193 #1186 StocktakePage reasons logic - #6
  src/database/UIDatabase.js
  src/globalStyles/index.js
  src/globalStyles/newDataTableStyles.js
  src/pages/StocktakeEditPage.js
  src/pages/dataTableUtilities/actions.js
  src/pages/dataTableUtilities/columns.js
  src/pages/dataTableUtilities/reducer/getReducer.js
  src/pages/dataTableUtilities/reducer/reducerMethods.js
  src/utilities/getModalTitle.js
  src/widgets/DataTable/DataTableRow.js
  src/widgets/DropDownCell.js
  src/widgets/icons.js
  src/widgets/index.js
  src/widgets/modals/DataTablePageModal.js
Labels: Priority: Immediate

#1192 #1129 New StocktakeEditPage - #5
  src/database/DataTypes/Stocktake.js
  src/database/UIDatabase.js
  src/globalStyles/index.js
  src/globalStyles/newDataTableStyles.js
  src/localization/modalStrings.js
  src/pages/StocktakeEditPage.js
  src/pages/dataTableUtilities/actions.js
  src/pages/dataTableUtilities/columns.js
  src/pages/dataTableUtilities/pageInfo.js
  src/pages/dataTableUtilities/reducer/getReducer.js
  src/pages/dataTableUtilities/reducer/reducerMethods.js
  src/utilities/formatters.js
  src/utilities/getModalTitle.js
  src/utilities/index.js
  src/utilities/sortDataBy.js
  src/widgets/DataTable/DataTableRow.js
  src/widgets/DropDownCell.js
  src/widgets/icons.js
  src/widgets/index.js
  src/widgets/modals/DataTablePageModal.js
  src/widgets/modals/ModalContainer.js
  src/widgets/modals/NewConfirmModal.js
  src/widgets/modals/NewStocktakeBatchModal.js
  src/widgets/modals/index.js
Labels: Priority: Immediate

#1191 #1130 New StocktakeManagePage - #4
  src/database/DataTypes/Item.js
  src/database/DataTypes/Stocktake.js
  src/database/UIDatabase.js
  src/globalStyles/index.js
  src/globalStyles/modalStyles.js
  src/globalStyles/newDataTableStyles.js
  src/localization/modalStrings.js
  src/navigation/actions.js
  src/pages/StocktakeEditPage.js
  src/pages/StocktakeManagePage.js
  src/pages/dataTableUtilities/actions.js
  src/pages/dataTableUtilities/columns.js
  src/pages/dataTableUtilities/pageInfo.js
  src/pages/dataTableUtilities/reducer/getReducer.js
  src/pages/dataTableUtilities/reducer/reducerMethods.js
  src/utilities/formatters.js
  src/utilities/getModalTitle.js
  src/utilities/index.js
  src/utilities/sortDataBy.js
  src/widgets/DataTable/DataTableRow.js
  src/widgets/DropDownCell.js
  src/widgets/icons.js
  src/widgets/index.js
  src/widgets/modals/BottomTextEditor.js
  src/widgets/modals/DataTablePageModal.js
  src/widgets/modals/ModalContainer.js
  src/widgets/modals/NewConfirmModal.js
  src/widgets/modals/NewStocktakeBatchModal.js
  src/widgets/modals/index.js
Labels: Priority: Immediate

#1190 #1131 New StocktakesPage - #3
  src/database/DataTypes/Item.js
  src/database/DataTypes/Stocktake.js
  src/database/UIDatabase.js
  src/globalStyles/index.js
  src/globalStyles/modalStyles.js
  src/globalStyles/newDataTableStyles.js
  src/localization/modalStrings.js
  src/navigation/actions.js
  src/pages/StocktakeEditPage.js
  src/pages/StocktakeManagePage.js
  src/pages/StocktakesPage.js
  src/pages/dataTableUtilities/actions.js
  src/pages/dataTableUtilities/columns.js
  src/pages/dataTableUtilities/pageInfo.js
  src/pages/dataTableUtilities/reducer/getReducer.js
  src/pages/dataTableUtilities/reducer/reducerMethods.js
  src/utilities/formatters.js
  src/utilities/getModalTitle.js
  src/utilities/index.js
  src/utilities/sortDataBy.js
  src/widgets/DataTable/DataTableRow.js
  src/widgets/DropDownCell.js
  src/widgets/icons.js
  src/widgets/index.js
  src/widgets/modals/BottomTextEditor.js
  src/widgets/modals/ByProgramModal.js
  src/widgets/modals/DataTablePageModal.js
  src/widgets/modals/ModalContainer.js
  src/widgets/modals/NewConfirmModal.js
  src/widgets/modals/NewStocktakeBatchModal.js
  src/widgets/modals/index.js
Labels: Priority: Immediate

#1189 #1134 New SupplierRequisitionPage - #2
  src/database/DataTypes/Item.js
  src/database/DataTypes/Period.js
  src/database/DataTypes/Stocktake.js
  src/database/UIDatabase.js
  src/globalStyles/buttonStyles.js
  src/globalStyles/index.js
  src/globalStyles/modalStyles.js
  src/globalStyles/newDataTableStyles.js
  src/localization/modalStrings.js
  src/navigation/actions.js
  src/pages/StocktakeEditPage.js
  src/pages/StocktakeManagePage.js
  src/pages/StocktakesPage.js
  src/pages/SupplierInvoicePage.js
  src/pages/SupplierRequisitionPage.js
  src/pages/SupplierRequisitionsPage.js
  src/pages/dataTableUtilities/actions.js
  src/pages/dataTableUtilities/columns.js
  src/pages/dataTableUtilities/pageInfo.js
  src/pages/dataTableUtilities/reducer/getReducer.js
  src/pages/dataTableUtilities/reducer/reducerMethods.js
  src/pages/index.js
  src/utilities/finalisation.js
  src/utilities/formatters.js
  src/utilities/getModalTitle.js
  src/utilities/index.js
  src/utilities/sortDataBy.js
  src/widgets/DataTable/DataTableRow.js
  src/widgets/DropDownCell.js
  src/widgets/icons.js
  src/widgets/index.js
  src/widgets/modals/BottomTextEditor.js
  src/widgets/modals/ByProgramModal.js
  src/widgets/modals/DataTablePageModal.js
  src/widgets/modals/ModalContainer.js
  src/widgets/modals/NewConfirmModal.js
  src/widgets/modals/NewStocktakeBatchModal.js
  src/widgets/modals/index.js
Labels: Priority: Immediate

#1188 #1135 New SupplierRequisitionsPage - #1
  src/database/DataTypes/Item.js
  src/database/DataTypes/Period.js
  src/database/DataTypes/Requisition.js
  src/database/DataTypes/Stocktake.js
  src/database/UIDatabase.js
  src/database/utilities/createRecord.js
  src/globalStyles/buttonStyles.js
  src/globalStyles/index.js
  src/globalStyles/modalStyles.js
  src/globalStyles/newDataTableStyles.js
  src/localization/modalStrings.js
  src/navigation/actions.js
  src/pages/StocktakeEditPage.js
  src/pages/StocktakeManagePage.js
  src/pages/StocktakesPage.js
  src/pages/SupplierInvoicePage.js
  src/pages/SupplierRequisitionPage.js
  src/pages/SupplierRequisitionsPage.js
  src/pages/dataTableUtilities/actions.js
  src/pages/dataTableUtilities/columns.js
  src/pages/dataTableUtilities/pageInfo.js
  src/pages/dataTableUtilities/reducer/getReducer.js
  src/pages/dataTableUtilities/reducer/reducerMethods.js
  src/pages/index.js
  src/utilities/finalisation.js
  src/utilities/formatters.js
  src/utilities/getModalTitle.js
  src/utilities/index.js
  src/utilities/sortDataBy.js
  src/widgets/DataTable/DataTableRow.js
  src/widgets/DropDownCell.js
  src/widgets/icons.js
  src/widgets/index.js
  src/widgets/modals/BottomTextEditor.js
  src/widgets/modals/ByProgramModal.js
  src/widgets/modals/DataTablePageModal.js
  src/widgets/modals/NewConfirmModal.js
  src/widgets/modals/NewStocktakeBatchModal.js
  src/widgets/modals/index.js
Labels: Priority: Immediate

#1256 #1250 column types constant
  src/pages/dataTableUtilities/constants.js
  src/pages/dataTableUtilities/getColumns.js
  src/pages/dataTableUtilities/index.js
  src/widgets/DataTable/DataTableRow.js
Labels: DataTable, Docs: not needed, Effort: small

#1266 #1249 extract state initialisers
  src/hooks/usePageReducer.js
  src/pages/CustomerInvoicePage.js
  src/pages/CustomerInvoicesPage.js
  src/pages/CustomerRequisitionPage.js
  src/pages/CustomerRequisitionsPage.js
  src/pages/StockPage.js
  src/pages/StocktakeEditPage.js
  src/pages/StocktakeManagePage.js
  src/pages/StocktakesPage.js
  src/pages/SupplierInvoicePage.js
  src/pages/SupplierInvoicesPage.js
  src/pages/SupplierRequisitionPage.js
  src/pages/SupplierRequisitionsPage.js
  src/pages/dataTableUtilities/getPageInitialiser.js
  src/pages/dataTableUtilities/index.js
  src/widgets/modals/NewStocktakeBatchModal.js
Labels: Bug: development, DataTable, Docs: not needed

#1308 #1263 migrate RealmExplorer
  .eslintrc
  src/pages/CustomerInvoicePage.js
  src/pages/CustomerRequisitionPage.js
  src/pages/CustomerRequisitionsPage.js
  src/pages/RealmExplorer.js
  src/pages/StockPage.js
  src/pages/StocktakeEditPage.js
  src/pages/StocktakeManagePage.js
  src/pages/StocktakesPage.js
  src/pages/SupplierInvoicePage.js
  src/pages/SupplierInvoicesPage.js
  src/pages/SupplierRequisitionPage.js
  src/pages/SupplierRequisitionsPage.js
  src/pages/dataTableUtilities/actions/constants.js
  src/pages/dataTableUtilities/actions/getPageActions.js
  src/pages/dataTableUtilities/index.js
  src/pages/dataTableUtilities/reducer/DataTablePageReducer.js
  src/pages/dataTableUtilities/reducer/cellReducers.js
  src/pages/dataTableUtilities/reducer/index.js
Labels: DataTable, Docs: not needed, Effort: medium

#1318 Fix incorrect ByProgramModal thresholdMOS
  src/widgets/modals/ByProgramModal.js
Labels: Bug: production, Docs: not needed, Effort: small
