Repository msupply-foundation/mobile, pull requests merged in 2020-01, with the labels that each got.

#1836 #1828 add indicator incoming sync
  src/sync/incomingSyncUtils.js
  src/sync/syncTranslators.js
Labels: Effort: medium, Feature, Module: indicators

#1846 #1823 add indicator database objects
  src/database/DataTypes/IndicatorAttribute.js
  src/database/DataTypes/IndicatorValue.js
  src/database/DataTypes/Period.js
  src/database/DataTypes/ProgramIndicator.js
  src/database/DataTypes/index.js
  src/database/schema.js
  src/sync/incomingSyncUtils.js
Labels: Effort: medium, Feature, Module: indicators

#1838 #1831 add indicator supplier ui
  android/app/src/main/res/drawable/picker_item.xml
  android/app/src/main/res/font/museo_500.otf
  android/app/src/main/res/font/sussol_font.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  src/globalStyles/buttonStyles.js
  src/globalStyles/index.js
  src/globalStyles/pickerStyles.js
  src/localization/programStrings.json
  src/pages/SupplierRequisitionPage.js
  src/widgets/DropDownCell.js
  src/widgets/index.js
Labels: Effort: medium, Feature, Module: indicators

#1841 #1829 add indicator toggle logic
  src/pages/SupplierRequisitionPage.js
  src/pages/dataTableUtilities/actions/constants.js
  src/pages/dataTableUtilities/actions/tableActions.js
  src/pages/dataTableUtilities/getPageDispatchers.js
  src/pages/dataTableUtilities/getPageInitialiser.js
  src/pages/dataTableUtilities/reducer/tableReducers.js
Labels: Docs: not needed, Effort: medium, Feature

#1843 #1842 add indicator row column relations
  src/database/DataTypes/IndicatorAttribute.js
  src/database/DataTypes/ProgramIndicator.js
  src/sync/incomingSyncUtils.js
Labels: Effort: small, Feature, Module: indicators

#1845 #1830 add indicator dynamic column logic
  src/database/DataTypes/MasterList.js
  src/pages/SupplierRequisitionPage.js
  src/pages/dataTableUtilities/actions/constants.js
  src/pages/dataTableUtilities/actions/tableActions.js
  src/pages/dataTableUtilities/getPageDispatchers.js
  src/pages/dataTableUtilities/getPageInitialiser.js
  src/pages/dataTableUtilities/reducer/tableReducers.js
  src/sync/incomingSyncUtils.js
  src/utilities/index.js
  src/utilities/mapIndicatorColumn.js
Labels: Docs: not needed, Effort: medium, Module: indicators

#1855 Add dropdown component
  src/globalStyles/index.js
  src/globalStyles/pickerStyles.js
  src/pages/SupplierRequisitionPage.js
  src/widgets/DropDown.js
  src/widgets/index.js
Labels: Effort: small, Feature, Module: indicators

#1857 Add DropDown component
  android/app/src/main/res/drawable/picker_item.xml
  android/app/src/main/res/font/museo_500.otf
  android/app/src/main/res/font/sussol_font.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  src/widgets/DropDown.js
Labels: Feature

#1851 #1848 add display indicator values
  src/database/DataTypes/IndicatorAttribute.js
  src/database/utilities/createRecord.js
  src/pages/SupplierRequisitionPage.js
  src/pages/dataTableUtilities/getPageInitialiser.js
  src/pages/dataTableUtilities/reducer/tableReducers.js
  src/utilities/getIndicatorTableData.js
  src/utilities/index.js
Labels: Docs: not needed, Effort: medium, Feature

#1910 #1877 edit indicator values
  src/database/DataTypes/IndicatorAttribute.js
  src/database/utilities/createRecord.js
  src/pages/SupplierRequisitionPage.js
  src/pages/dataTableUtilities/actions/cellActions.js
  src/pages/dataTableUtilities/getPageDispatchers.js
  src/pages/dataTableUtilities/reducer/cellReducers.js
  src/sync/incomingSyncUtils.js
  src/utilities/getIndicatorTableData.js
  src/utilities/index.js
Labels: Effort: medium, Feature, Module: indicators

#1911 #1903 update indicators column codes
  src/utilities/getIndicatorTableData.js
Labels: Bug: development, Docs: not needed, Effort: small

#1914 Add indicator attributes to outgoing sync
  src/sync/SyncQueue.js
  src/sync/outgoingSyncUtils.js
Labels: Docs: not needed, Effort: small, Feature

#1918 #1902 fix supplier requisition no indicator error
  src/database/DataTypes/Requisition.js
  src/pages/SupplierRequisitionPage.js
  src/pages/dataTableUtilities/getPageInitialiser.js
Labels: Bug: development, Docs: not needed, Effort: small

#1919 #1901 move indicator helpers
  src/pages/dataTableUtilities/actions/cellActions.js
  src/pages/dataTableUtilities/getIndicatorTableData.js
  src/pages/dataTableUtilities/getPageInitialiser.js
  src/pages/dataTableUtilities/index.js
  src/pages/dataTableUtilities/reducer/cellReducers.js
  src/pages/dataTableUtilities/reducer/tableReducers.js
  src/utilities/index.js
Labels: Docs: not needed, Effort: small, Feature

#1923 #1915 tidy up indicator utilities
  src/pages/dataTableUtilities/actions/cellActions.js
  src/pages/dataTableUtilities/getIndicatorTableData.js
  src/pages/dataTableUtilities/reducer/cellReducers.js
Labels: Docs: not needed, Effort: small, Feature

#2024 Add remove overpayments from pay
  src/utilities/modules/dispensary/pay.js
Labels: Bug: development, Docs: not needed, Effort: small, Module: dispensary, Priority: high
