Repository msupply-foundation/mobile, pull requests merged in 2022-03, with the labels that each got.

#4599 #4592 Fix Response requisition rouge CI problem
  src/database/DataTypes/Requisition.js
  src/pages/CustomerRequisitionsPage.js
Labels: Priority: high, Bug: production, Needs testing, Effort: medium, Investigation, needs discussion, Docs: internal

#4608 #4562 Customer Requisition with no Supplied quantity creates blank CI when finalised
  src/database/DataTypes/Requisition.js
  src/database/DataTypes/RequisitionItem.js
  src/localization/modalStrings.json
Labels: Priority: normal, Bug: production, Effort: medium, Investigation, Docs: internal

#4622 #4618 fix translation script export non existing lang
  dev_scripts/translation.js
Labels: Bug: development

#4621 #4613 Translate remaining strings to Pt
  src/globalStyles/buttonStyles.js
  src/localization/authStrings.json
  src/localization/buttonStrings.json
  src/localization/demoUserModalStrings.json
  src/localization/dispensingStrings.json
  src/localization/formInputStrings.json
  src/localization/generalStrings.json
  src/localization/modalStrings.json
  src/localization/navStrings.json
  src/localization/pageInfoStrings.json
  src/localization/programStrings.json
  src/localization/reportStrings.json
  src/localization/syncStrings.json
  src/localization/tableStrings.json
  src/localization/utilities.js
  src/localization/vaccineStrings.json
  src/pages/MenuPage.js
Labels: Feature, Priority: unconfirmed

#4627 #4486 fix unlocalised strings
  src/authentication/Helpers.ts
  src/localization/authStrings.json
  src/localization/utilities.js
  src/localization/vaccineStrings.json
  src/pages/NewSensor/BreachConfigRow.js
  src/pages/VaccinePage.js
Labels: Priority: low, Bug: production, Status: Backlog

#4628 #4625 fix language effect on menu app
  src/actions/UserActions.js
  src/pages/MenuPage.js
  src/reducers/UserReducer.js
  src/widgets/modals/LoginModal.js
  src/widgets/modals/index.js
Labels: Bug: development

#4643 #4640 Showing invalid date
  src/utilities/formatters.js
Labels: Bug: ????
