Repository msupply-foundation/mobile, pull requests merged in 2022-04, with the labels that each got.

#4651 Added transact id
  src/actions/Entities/NameNoteActions.js
  src/actions/Entities/VaccinePrescriptionActions.js
Labels: Feature, Priority: unconfirmed

#4648 #4563 Updated French translations from spreadsheet
  src/globalStyles/pageStyles.js
  src/localization/buttonStrings.json
  src/localization/pageInfoStrings.json
  src/localization/tableStrings.json
Labels: Priority: normal, Feature, Status: In PR

#4654 #4644 Update to use selected language rather than previous language
  src/widgets/modals/LoginModal.js
Labels: Bug: development
