Repository msupply-foundation/mobile, pull requests merged in 2022-08, with the labels that each got.

#4880 #4871 App hangs/keeps on loading forever when OK button is clicked multiple times while entering a vaccination event
  src/widgets/Tabs/VaccineSelect.js
Labels: Priority: high, Bug: production, Project: Kiribati COVID-19 Vax

#4881 #4842 Fix Deleted patients again shows up
  src/actions/PatientActions.js
  src/globalStyles/dataTableStyles.js
  src/hooks/useLocalAndRemotePatients.js
  src/localization/dispensingStrings.json
  src/localization/generalStrings.json
  src/reducers/PatientReducer.js
  src/sync/lookupApiUtils.js
  src/widgets/SimpleTable.js
  src/widgets/modals/SearchForm.js
Labels: Priority: high, Bug: development, Project: Kiribati COVID-19 Vax

#4882 #4841 Fix lookup patient overriding current changes
  package.json
  src/localization/dispensingStrings.json
  src/widgets/modals/SearchForm.js
Labels: Priority: high, Bug: development, Project: Kiribati COVID-19 Vax, Solution: Agreed

#4893 #4885 Disable deleted patient from being given vaccine
  src/widgets/Tabs/PatientSelect.js
Labels: Effort: medium, Priority: release blocker, Docs: not needed, Bug: development, Project: Kiribati COVID-19 Vax

#4895 #4887 New patient button should only go to tab 2 in Vaccine dispensing
  src/widgets/Tabs/PatientSelect.js
Labels: Bug: production, Priority: immediate, Project: Kiribati COVID-19 Vax

#4896 #4886 App hangs/keeps on loading forever when OK&Next button is clicked multiple times while entering a vaccination event
  src/widgets/Tabs/VaccineSelect.js
Labels: Priority: high, Bug: ????, Project: Kiribati COVID-19 Vax

#4899 #4888 Fix app crashes on tapping save changes button multiple times
  src/widgets/VaccinatorDropDown.js
  src/widgets/modals/VaccinationEvent.js
Labels: Bug: production, Priority: immediate, Project: Kiribati COVID-19 Vax
