Repository msupply-foundation/mobile, pull requests merged in 2022-09, with the labels that each got.

#4912 #4911 when new vaccine event is created all other vaccine events of the patient are updated along with it causing sync issues
  src/actions/Entities/NameActions.js
  src/actions/Entities/NameNoteActions.js
  src/actions/PatientActions.js
  src/database/utilities/createRecord.js
  src/utilities/checkIsObject.js
  src/utilities/index.js
Labels: Effort: medium, Bug: development, Project: Kiribati COVID-19 Vax

#4914 #4913 Vax event creation and editing should not trigger patient update if the current store is not patient's home store
  src/actions/Entities/VaccinePrescriptionActions.js
Labels: Priority: immediate, Bug: development, Project: Kiribati COVID-19 Vax, Solution: Agreed

#4919 #4909 Subpage 2 Additional details' changes are overridden by Subpage 3 Vax Event changes
  src/widgets/modals/VaccinationEvent.js
Labels: Priority: high, Bug: ????, Project: Kiribati COVID-19 Vax

#4921 #4920 Patient homes store vax event error
  src/actions/Entities/NameActions.js
  src/actions/Entities/VaccinePrescriptionActions.js
Labels: Effort: medium, Bug: development, Project: Kiribati COVID-19 Vax

#4926 #4925 Event details subform save buttons are not behaving consistently
  src/widgets/JSONForm/widgets/Checkboxes.js
  src/widgets/JSONForm/widgets/Select.js
  src/widgets/modals/VaccinationEvent.js
Labels: Priority: high, Bug: development, Project: Kiribati COVID-19 Vax

#4897 #4894 fixed toggle failure of current stock and stocktake
  src/pages/dataTableUtilities/reducer/tableReducers.js
Labels: Bug: ????

#4933 #4892 Fix dob field issues
  src/widgets/FormInputs/FormDOBInput.js
  src/widgets/JSONForm/widgets/DatePicker.js
Labels: Priority: normal, Effort: medium, Bug: development, Project: Kiribati COVID-19 Vax
