Repository msupply-foundation/mobile, pull requests merged in 2022-02, with the labels that each got.

#4574 Add restarting scheduler on mount
  package.json
  src/actions/Bluetooth/SensorDownloadActions.js
  src/mSupplyMobileApp.js
  src/reducers/Bluetooth/SensorDownloadReducer.js
Labels: Bug: production, Investigation

#4575 #4525 Make the menu button a tiny bit wider
  package.json
  src/globalStyles/buttonStyles.js
Labels: bugsnag, 8.2.3

#4581 Release 8.4.2
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/xml/network_security_config.xml
  package.json
Labels: Release Discussion
