Repository msupply-foundation/mobile, pull requests merged in 2022-11, with the labels that each got.

#4988 #4987 Fix React-native failed to build
  android/build.gradle
Labels: Priority: immediate, Bug: development, Solution: Agreed

#4973 #4949 allow setting editable from login page
  .env.example
  .gitignore
  babel.config.js
  package.json
  src/pages/MenuPage.js
  src/pages/SettingsPage.js
  src/widgets/modals/LoginModal.js
  yarn.lock
Labels: Priority: high

#4994 #4993 Add support for asdf
  .tool-versions
Labels: Priority: low, Effort: small, Solution: Agreed, Type: Enhancement

#5001 #4997 setting moved to left to language button on login form
  src/widgets/modals/LoginModal.js
Labels: Priority: low, Effort: small, Docs: not needed, Solution: Agreed, Type: Enhancement

#5002 #4996 Label updated as per password preference
  src/localization/modalStrings.json
  src/pages/SettingsPage.js
  src/utilities/getModalTitle.js
  src/widgets/modals/DataTablePageModal.js
  src/widgets/modals/LoginModal.js
Labels: Priority: normal, Effort: small, Type: Enhancement
