Repository msupply-foundation/mobile, pull requests merged in 2022-12, with the labels that each got.

#5018 Remove JSON.stringify so that createCustomerInvoice method's JSON.str…
  src/widgets/modals/VaccinationEvent.js
Labels: Priority: high, Effort: small, Docs: not needed, Bug: development, 8.6.1

#4784 #4678 - Stopping app to crash
  src/pages/dataTableUtilities/actions/rowActions.js
Labels: Priority: high, Effort: medium, Bug: development, 8.4.2

#5029 #4974 stocktake reason should be mandatory
  src/database/DataTypes/Stocktake.js
  src/database/DataTypes/StocktakeItem.js
  src/localization/modalStrings.json
Labels: Priority: normal, Bug: production, Effort: small, Type: Enhancement
