Repository msupply-foundation/mobile, pull requests merged in 2022-07, with the labels that each got.

#4777 #4775 Flags to allow soft deletion of name notes and patients
  src/database/DataTypes/Name.js
  src/database/DataTypes/NameNote.js
  src/database/schema.js
  src/hooks/useLocalAndRemotePatients.js
  src/selectors/Entities/name.js
  src/selectors/dispensary.js
  src/sync/incomingSyncUtils.js
  src/sync/outgoingSyncUtils.js
Labels: Priority: normal, Feature

#4778 #4715 edit vaccination transact data via vaccination event modal
  src/actions/Entities/VaccinePrescriptionActions.js
  src/database/utilities/createRecord.js
  src/localization/modalStrings.json
  src/localization/vaccineStrings.json
  src/navigation/constants.js
  src/pages/CustomerInvoicePage.js
  src/pages/dataTableUtilities/getColumns.js
  src/reducers/Entities/VaccinePrescriptionReducer.js
  src/selectors/Entities/vaccinePrescription.js
  src/widgets/PaperModal/PaperConfirmModal.js
  src/widgets/VaccinatorDropDown.js
  src/widgets/VaccinePrescriptionInfo.js
  src/widgets/modals/VaccinationEvent.js
Labels: Feature, Priority: unconfirmed

#4798 #4796 Kiribati: soft delete of vaccinations
  src/actions/Entities/NameNoteActions.js
  src/actions/Entities/VaccinePrescriptionActions.js
  src/database/DataTypes/NameNote.js
  src/database/utilities/createRecord.js
  src/localization/buttonStrings.json
  src/localization/modalStrings.json
  src/reducers/Entities/NameNoteReducer.js
  src/widgets/modals/VaccinationEvent.js
Labels: Feature, Priority: unconfirmed, Project: Kiribati COVID-19 Vax

#4794 #4792 Kiribati: Prevent giving vaccine to deceased patient
  src/localization/modalStrings.json
  src/widgets/CircleButton.js
  src/widgets/FormInputs/FormToggle.js
  src/widgets/Tabs/PatientEdit.js
  src/widgets/Tabs/PatientSelect.js
  src/widgets/ToggleBar/ToggleBar.js
Labels: Feature, Project: Kiribati COVID-19 Vax

#4804 #4801 Kiribati: a pop-up message to contain the name of the store where vaccination was made
  src/localization/modalStrings.json
  src/widgets/modals/VaccinationEvent.js
Labels: Feature, Priority: unconfirmed, Project: Kiribati COVID-19 Vax

#4806 #4792 Bug fixed
  src/widgets/Tabs/PatientSelect.js
Labels: Feature, Project: Kiribati COVID-19 Vax

#4807 #4805 Editing vaccination event detail is very inconsistent
  src/globalStyles/buttonStyles.js
  src/sync/lookupApiUtils.js
  src/widgets/Stepper.js
  src/widgets/Tabs/PatientSelect.js
  src/widgets/modals/VaccinationEvent.js
Labels: Priority: high, Bug: development, Project: Kiribati COVID-19 Vax

#4812 #4802 Kiribati: Delete patient medical record
  src/actions/PatientActions.js
  src/database/utilities/createRecord.js
  src/localization/dispensingStrings.json
  src/localization/generalStrings.json
  src/localization/modalStrings.json
  src/reducers/PatientReducer.js
  src/selectors/dispensary.js
  src/selectors/patient.js
  src/widgets/modalChildren/PatientEditModal.js
  yarn.lock
Labels: Priority: high, Feature, Project: Kiribati COVID-19 Vax
