Repository msupply-foundation/mobile, pull requests merged in 2023-01, with the labels that each got.

#5031 5004 number records removed from sync
  src/dataMigration.js
  src/database/utilities/constants.js
  src/database/utilities/createRecord.js
  src/database/utilities/index.js
  src/database/utilities/numberSequence.js
  src/mSupplyMobileApp.js
  src/pages/MenuPage.js
  src/pages/StocktakeManagePage.js
  src/sync/SyncQueue.js
  src/sync/incomingSyncUtils.js
  src/sync/outgoingSyncUtils.js
  src/sync/syncTranslators.js
  src/widgets/withOnePress.js
Labels: Priority: high, Effort: medium, Type: Enhancement

#5046 5037 Fix reason would not show on Requisition on Remote desktop
  src/sync/incomingSyncUtils.js
  src/sync/outgoingSyncUtils.js
Labels: Priority: high, Bug: production, Effort: medium, Docs: internal

#5058 App crashes while creating policy in prescription dispensing
  src/widgets/FormInputs/FormSlider.js
Labels: Priority: high, Bug: production, Effort: small, Bug: development, Solution: Agreed

#5057 5044 not able to create a patients
  src/widgets/modalChildren/PatientEditModal.js
Labels: Effort: medium, Priority: release blocker, Bug: development

#5062 5061 Viewing indicators app crashes
  src/database/utilities/createRecord.js
Labels: Priority: high, Effort: small, Bug: development

#5047 #5039 Stocktake reasoning resolved
  src/database/DataTypes/Stocktake.js
  src/database/DataTypes/StocktakeItem.js
Labels: Bug: development, Status: In progress

#5070 5068 Fix New Stock take crashes
  src/pages/StocktakeManagePage.js
  src/utilities/checkIsObject.js
  src/utilities/index.js
Labels: Effort: medium, Priority: immediate, Bug: development
