Repository msupply-foundation/mobile, pull requests merged in 2023-02, with the labels that each got.

#5087 #5086 Reason column should be visible to all items
  src/widgets/modals/StocktakeBatchModal.js
Labels: Effort: medium, Priority: immediate, Bug: ????, Status: In progress, Solution: Agreed

#5084 #5080 Fix crash when Entering The Details of Insurance Policy in Mobile App
  src/pages/DispensingPage.js
  src/pages/PrescriptionPage.js
  src/widgets/FormControl.js
  src/widgets/FormInputs/index.js
  src/widgets/index.js
  src/widgets/modalChildren/ADRInput.js
  src/widgets/modalChildren/PatientEditModal.js
  src/widgets/modalChildren/index.js
  src/widgets/modals/InsurancePolicyModel.js
  src/widgets/modals/PrescriberModel.js
  src/widgets/modals/index.js
Labels: Effort: medium, Bug: development, 8.6.2-rc04

#5098 5097 Fix Instances of same model in different nested routes opens multiple models in background
  src/widgets/modalChildren/PatientEditModal.js
  src/widgets/modals/InsurancePolicyModel.js
  src/widgets/modals/PrescriberModel.js
Labels: Priority: normal, Effort: small, Type: Enhancement

#5103 5099 Stocktake batch sell price crash
  src/pages/dataTableUtilities/actions/cellActions.js
  src/widgets/modals/StocktakeBatchModal.js
Labels: Priority: normal, Bug: production

#5102 5101 Patient survey demographic data does not load
  src/database/utilities/createRecord.js
  src/widgets/PrescriptionInfo.js
Labels: Bug: production, Effort: medium, Priority: immediate, Project: Kiribati COVID-19 Vax, Solution: Agreed

#5107 Release v8.6.2
  .env.example
  .gitignore
  .tool-versions
  README.md
  android/build.gradle
  babel.config.js
  package.json
  src/authentication/UserAuthenticator.js
  src/dataMigration.js
  src/database/DataTypes/Stocktake.js
  src/database/utilities/constants.js
  src/database/utilities/createRecord.js
  src/database/utilities/index.js
  src/database/utilities/numberSequence.js
  src/localization/modalStrings.json
  src/mSupplyMobileApp.js
  src/pages/DispensingPage.js
  src/pages/MenuPage.js
  src/pages/PrescriptionPage.js
  src/pages/SettingsPage.js
  src/pages/StocktakeManagePage.js
  src/pages/dataTableUtilities/actions/cellActions.js
  src/pages/dataTableUtilities/actions/rowActions.js
  src/sync/SyncQueue.js
  src/sync/incomingSyncUtils.js
  src/sync/outgoingSyncUtils.js
  src/sync/syncTranslators.js
  src/utilities/checkIsObject.js
  src/utilities/getModalTitle.js
  src/utilities/index.js
  src/widgets/FormControl.js
  src/widgets/FormInputs/FormSlider.js
  src/widgets/FormInputs/index.js
  src/widgets/PrescriptionInfo.js
  src/widgets/index.js
  src/widgets/modalChildren/ADRInput.js
  src/widgets/modalChildren/PatientEditModal.js
  src/widgets/modalChildren/index.js
  src/widgets/modals/DataTablePageModal.js
  src/widgets/modals/InsurancePolicyModel.js
  src/widgets/modals/LoginModal.js
  src/widgets/modals/PrescriberModel.js
  src/widgets/modals/StocktakeBatchModal.js
  src/widgets/modals/VaccinationEvent.js
  src/widgets/modals/index.js
  src/widgets/withOnePress.js
  yarn.lock
Labels: Priority: immediate, Bug: development, Status: Done, Solution: Agreed

#5104 #5090 finalise requisition with zero quantity lines
  src/database/DataTypes/Requisition.js
  src/database/utilities/preferenceConstants.js
Labels: Priority: normal, Customization: Ivory Coast, Solution: Agreed

#5110 #5100 Chinese translation
  src/images/flags/ch.png
  src/localization/authStrings.json
  src/localization/buttonStrings.json
  src/localization/demoUserModalStrings.json
  src/localization/dispensingStrings.json
  src/localization/formInputStrings.json
  src/localization/generalStrings.json
  src/localization/index.ts
  src/localization/modalStrings.json
  src/localization/navStrings.json
  src/localization/pageInfoStrings.json
  src/localization/programStrings.json
  src/localization/reportStrings.json
  src/localization/syncStrings.json
  src/localization/tableStrings.json
  src/localization/vaccineStrings.json
  src/localization/validationStrings.json
  src/widgets/Flag.js
  src/widgets/images.js
Labels: Priority: normal, Type: Feature, Effort: medium, Docs: public, Solution: Agreed
